spring.application.name=solestyle-backend

spring.datasource.url=jdbc:mysql://localhost:3306/solestyle?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Pratham@4912

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

razorpay.key.id=rzp_test_TYPgbWRMoGYY2L
razorpay.key.secret=B2YuaKjp9qZPvXzA7G91Qsg5